onnx/sigs

converters/meetings/001-20190703.md

Add the basic information for the converters kick off
meeting.

Add kick off meeting

---

converters/meetings/002-20190724.md

Add converters meeting doc for 7/24

Add converters meeting doc for 7/24

---

converters/meetings/004-20190905.md

Add Converters SIG meeting notes for 09/05/2019

Add meeting notes for 09/05/2019

---

converters/docs/ConvertersDashboard.md
converters/meetings/006-20191003.md

Add coverage dashboard for all converters and runtimes. Also add
the meeting notes for 10/03.

Add coverage dashboard and meeting notes 10/03

---

converters/meetings/008-20191206.md

Add meeting notes for Converters SIG 12/06

Add meeting notes for Converters SIG 12/06

---

models-tutorials/README.md
models-tutorials/docs/MissionStatement.md

Adding priorities / mission statement proposal for the Model Zoo SIG

Model Zoo + Tutorials SIG proposal

---

models-tutorials/docs/MissionStatement.md

Adding a mission statement for Model Zoo + Tutorials SIG

---

converters/meetings/009-20200116.md

Add Converters SIG meeting notes for 1/16/2020

Add Converters SIG meeting notes for 1/16/2020

---

models-tutorials/README.md
models-tutorials/docs/CommunityEvents.md
models-tutorials/meetings/001-20200130.md

Add meeting minutes for first ONNX model zoo + tutorials SIG meeting

Update first meeting minutes, README, Community Events list

---

models-tutorials/docs/CommunityEvents.md

Added O'Reilly Strata Data and AI, Codemotion Rome, a Meetup and a conference in Amsterdam.

Add upcoming events where IBMers will present on ONNX. 

---

converters/meetings/010-20200214.md

Add Converters SIG Meeting Notes for 02/14/2020

Add Converters SIG Meeting Notes for 02/14/2020

---

models-tutorials/meetings/002-20200309.md

Add minutes from Meeting 2 (Model Zoo + Tutorials)

---

converters/meetings/012-20200424.md

Add converters SIG meeting notes for 04/24/2020

Add converters SIG meeting notes for 04/24/2020

---

converters/meetings/013-20200522.md

Add Converters meeting notes for 5/22/2020

Add Converters meeting notes for 5/22/2020

---

models-tutorials/README.md
models-tutorials/meetings/003-20200413.md

Meeting minutes for Model Zoo meeting 3

---

converters/meetings/014-20200612.md

Add Converters SIG meeting notes for 06/12/2020

Add Converters SIG meeting notes for 06/12/2020

---

CONTRIBUTORS
README.md

As discussed in 7/25 steering committee meeting.

Make list of Contributors and Approvers transparent

---

converters/meetings/014-20200724.md

Add converters SIG meeting notes for 07/24/2020

Add converters SIG meeting notes for 07/24/2020

---

converters/meetings/015-20200911.md

Add Converters SIG meeting notes for 09/11/2020

Add Converters SIG meeting notes for 09/11/2020

---

CONTRIBUTORS

Both Scott and Hari have made significant contributions to onnx hence adding them as contributors.

propose contributors for arch infra and operators sigs

---

CONTRIBUTORS

work as the model zoo sig lead.

Add wenbingl as the approver for model zoo.

---

CONTRIBUTORS

@onnx/steering-committee  please review and approve
After that, I will merge once the permissions are updated

add optimizer maintainers

---

infra/meetings/003-20201120

Signed-off-by: Ashwini Khade <askhade@microsoft.com>

meeting notes

---

converters/meetings/018-20210114.md

Add Converters SIG meeting notes for 1/14/2021
Signed-off-by: Chin Huang <chhuang@us.ibm.com>

Add Converters SIG meeting notes for 1/14/2021

---

converters/meetings/019-20210212.md

Add converters SIG meeting notes for 02/12/2021
Signed-off-by: Chin Huang <chhuang@us.ibm.com>

Add converters SIG meeting notes for 02/12/2021

---

operators/meetings/019-20210318.md

Signed-off-by: Michal Karzynski <michal.karzynski@intel.com>

Operators SIG meeting notes for March 18, 2021

---

operators/meetings/020-20210415.md

Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>

Meeting notes (April 2021)

---

CONTRIBUTORS

Removed members who have been inactive for more than 12 months per https://github.com/onnx/onnx/tree/master/community
Signed-off-by: Prasanth Pulavarthi <prasanth.pulavarthi@microsoft.com>

Update ModelZooTutorials SIG membership

---

CONTRIBUTORS

Remove inactive members per https://github.com/onnx/onnx/tree/master/community
Add @TomWildenhain-Microsoft for his contributions to the tf2onnx converter.
Add @kevinch-nv as approver for his management of the onnx-tensorrt converter.
Approved by @guschmue (MS) and @chinhuang007 (IBM). No objections to new approver from other SIG leads.

Update Converters SIG membership

---

CONTRIBUTORS

Remove inactive members as per https://github.com/onnx/onnx/tree/master/community
Move yuanbyu from MLIR to regular contributor
Approved by @askhade (MS) and @linkerzhang (Alibaba)

Update ArchInfra SIG membership

---

operators/README.md

Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>

Add SIG meeting details

---

operators/meetings/022-20210610.md

Signed-off-by: Michal Karzynski <michal.karzynski@intel.com>

Operators SIG meeting notes

---

converters/meetings/021-20210625.md

Add Converters SIG meeting notes for 6/25/2021
Signed-off-by: Chin Huang <chhuang@us.ibm.com>

Add Converters SIG meeting notes for 6/25/2021

---

CONTRIBUTORS
operators/README.md

Adding Ashwini to approver list for Operator SIG.

Operator SIG approver update

---

operators/meetings/024-20210805.md

Signed-off-by: Michal Karzynski <michal.karzynski@intel.com>

Operators SIG meeting notes August 5, 2021

---

operators/meetings/025-20210902.md

Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>

Meeting notes for Sept 2nd meeting

---

CONTRIBUTORS

Signed-off-by: Prasanth Pulavarthi <prasanth.pulavarthi@microsoft.com>

Update steering committee handles for this year

---

CONTRIBUTORS

Signed-off-by: Prasanth Pulavarthi <prasanth.pulavarthi@microsoft.com>

Update SIG chairs and WG leads

---

CONTRIBUTORS

This makes it slightly easier to navigate these long lists.

sort and remove trailing spaces

---

CONTRIBUTORS

We've both recently started spending significant amounts of time on
ONNX (through our jobs at Microsoft). E.g., recent commits:
<https://github.com/onnx/onnx/commits?author=garymm>
<https://github.com/onnx/onnx/commits?author=liqunfu>

Add garymm and liqunfu as contributors

---

CONTRIBUTORS

Signed-off-by: Liqun Fu <liqfu@microsoft.com>

add jacky and liqun to archinfra approvers

---

CONTRIBUTORS

Add 3 active contributors for SIG-modelstutorials
- AK391 contributes live demo with ONNX Model Zoo models in Hugging Face Spaces
- (New) mengniwang95 contributes a lot of int8 ONNX models in the past year
- mhamilton723 contributes ONNX hub to have an API for downloading ONNX Model Zoo models

Add 3 active contributors for SIG-modelstutorials

---

CONTRIBUTORS
converters/README.md
infra/README.md
operators/meetings/029-20220428.md

Signed-off-by: Liqun Fu <liqfu@microsoft.com>

update contributors for onnx repo

---

operators/meetings/030-20220526 copy.md

Add minutes of the May 22 meeting

Add minutes of the May 22 meeting

---

CONTRIBUTORS

Add @daquexian to approver list, and @p-wysocki to contributor list.

Update contributor/approver list

---

operators/meetings/033-20220825.md

Signed-off-by: Michal Karzynski <michal.karzynski@intel.com>

Meeting notes for Operator SIG August 25th, 2022

---

README.md
best-practices.md
models-tutorials/README.md
operators/README.md

Signed-off-by: andife <fehlner@arcor.de>

gitter -> slack, master -> main, spelling

---

compilers/README.md

added the link to the newly created onnx-compiler channel

Added link to a newly created onnx-compiler channel

---

README.md

Sort alphabetically

---

CONTRIBUTORS

* Removed Gary Miguel and Aishwarya who no longer contribute to ONNX
* Added Thiago Crepaldi as ONNX operator contributor. Las contribution was Col2Im op

Update Microsoft contributors for ONNX

---

compilers/meetings/sig-compiler-2023-04-04.md

could not add a file using the web interface in an empty did. Added a file to remedy this.

added file in compiler/meeting folder

---

operators/meetings/039-20230504.md

May 2023 sig meeting minutes

---

operators/meetings/046-20240201.md

Feb 2024 meeting minutes

---

CONTRIBUTORS

Add Javier to Models and Tutorials SIG contributor list

Update contributor list

---

operators/meetings/051-20240822.md

August 2024 meeting minutes

---

operators/meetings/053-20241024.md

Meeting minutes of the operator SIG meeting (Oct 2024)

Meeting minutes of the operator SIG meeting (Oct 2024)

---

CONTRIBUTORS

Update the sig leads for SIG arch&infra

update SIG leads for arch&infra

---

CONTRIBUTORS

Create onnx-ir section under SIG-archinfra for repository specific maintainers.

Create onnx-ir section under SIG-archinfra
